In [ ]:
'''
.       - Any Character Except New Line
\d      - Digit (0-9)
\D      - Not a Digit (0-9)
\w      - Word Character (a-z, A-Z, 0-9, _)
\W      - Not a Word Character
\s      - Whitespace (space, tab, newline)
\S      - Not Whitespace (space, tab, newline)

\b      - Word Boundary
\B      - Not a Word Boundary
^       - Beginning of a String
$       - End of a String

[]      - Matches Characters in brackets
[^ ]    - Matches Characters NOT in brackets
|       - Either Or
( )     - Group

Quantifiers:
*       - 0 or More
+       - 1 or More
?       - 0 or One
{3}     - Exact Number
{3,4}   - Range of Numbers (Minimum, Maximum)
'''

In [60]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
mohammed.israr11.com
321-555-4321
123.555.1234
123*555*1234
123.555.1234
800-555-1234
900-555-1234
987000000000
134000007770
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''


In [4]:
import re

In [19]:
# [ matches the char in brackets]
a = re.compile(r'[ab]')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(82, 83), match='a'>
<re.Match object; span=(85, 86), match='a'>
<re.Match object; span=(87, 88), match='a'>
<re.Match object; span=(92, 93), match='a'>
<re.Match object; span=(95, 96), match='a'>
<re.Match object; span=(97, 98), match='a'>
<re.Match object; span=(113, 114), match='b'>
<re.Match object; span=(119, 120), match='a'>
<re.Match object; span=(157, 158), match='a'>
<re.Match object; span=(166, 167), match='a'>
<re.Match object; span=(260, 261), match='a'>
<re.Match object; span=(278, 279), match='a'>
<re.Match object; span=(290, 291), match='b'>


In [15]:
# [ matches the char in brackets]
a = re.compile(r'[0-9A-Za-z]')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(3, 4), match='c'>
<re.Match object; span=(4, 5), match='d'>
<re.Match object; span=(5, 6), match='e'>
<re.Match object; span=(6, 7), match='f'>
<re.Match object; span=(7, 8), match='g'>
<re.Match object; span=(8, 9), match='h'>
<re.Match object; span=(9, 10), match='i'>
<re.Match object; span=(10, 11), match='j'>
<re.Match object; span=(11, 12), match='k'>
<re.Match object; span=(12, 13), match='l'>
<re.Match object; span=(13, 14), match='m'>
<re.Match object; span=(14, 15), match='n'>
<re.Match object; span=(15, 16), match='o'>
<re.Match object; span=(16, 17), match='p'>
<re.Match object; span=(17, 18), match='q'>
<re.Match object; span=(18, 19), match='u'>
<re.Match object; span=(19, 20), match='r'>
<re.Match object; span=(20, 21), match='t'>
<re.Match object; span=(21, 22), match='u'>
<re.Match object; span=(22, 23), match='v'>
<re.Match object; span=(23, 24), match='w'>
<re.M

In [16]:
# [ matches the char in brackets]
a = re.compile(r'[^a-f]')
# From where you want to match
b = a.finditer('Hey there thiis is python class')

for i in b:
    print(i)

<re.Match object; span=(0, 1), match='H'>
<re.Match object; span=(2, 3), match='y'>
<re.Match object; span=(3, 4), match=' '>
<re.Match object; span=(4, 5), match='t'>
<re.Match object; span=(5, 6), match='h'>
<re.Match object; span=(7, 8), match='r'>
<re.Match object; span=(9, 10), match=' '>
<re.Match object; span=(10, 11), match='t'>
<re.Match object; span=(11, 12), match='h'>
<re.Match object; span=(12, 13), match='i'>
<re.Match object; span=(13, 14), match='i'>
<re.Match object; span=(14, 15), match='s'>
<re.Match object; span=(15, 16), match=' '>
<re.Match object; span=(16, 17), match='i'>
<re.Match object; span=(17, 18), match='s'>
<re.Match object; span=(18, 19), match=' '>
<re.Match object; span=(19, 20), match='p'>
<re.Match object; span=(20, 21), match='y'>
<re.Match object; span=(21, 22), match='t'>
<re.Match object; span=(22, 23), match='h'>
<re.Match object; span=(23, 24), match='o'>
<re.Match object; span=(24, 25), match='n'>
<re.Match object; span=(25, 26), match=' '>
<

In [29]:
# [ matches the char in brackets]
a = re.compile(r'\b[^b]at')
# From where you want to match
b = a.finditer('cat bat fat mat pat sohat that')

for i in b:
    print(i)

<re.Match object; span=(0, 3), match='cat'>
<re.Match object; span=(8, 11), match='fat'>
<re.Match object; span=(12, 15), match='mat'>
<re.Match object; span=(16, 19), match='pat'>


In [36]:
# {} - 

# [ matches the char in brackets]
a = re.compile(r'\d{3}[-*]\d{3}[*-]\d{4}')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(57, 69), match='321-555-4321'>
<re.Match object; span=(175, 187), match='321-555-4321'>
<re.Match object; span=(201, 213), match='123*555*1234'>
<re.Match object; span=(227, 239), match='800-555-1234'>
<re.Match object; span=(240, 252), match='900-555-1234'>


In [39]:
# {} - 

# [ matches the char in brackets]
a = re.compile(r'[98]\d{10}')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(253, 264), match='98700000000'>


In [45]:
# {min, max} - 

# [ matches the char in brackets]
a = re.compile(r'[^89]\d{2}[-.]\d{3}[-.]\d{4}')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(57, 69), match='321-555-4321'>
<re.Match object; span=(175, 187), match='321-555-4321'>
<re.Match object; span=(188, 200), match='123.555.1234'>
<re.Match object; span=(214, 226), match='123.555.1234'>


In [46]:
# step 1

# [ matches the char in brackets]
a = re.compile(r'M')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(40, 41), match='M'>
<re.Match object; span=(89, 90), match='M'>
<re.Match object; span=(279, 280), match='M'>
<re.Match object; span=(291, 292), match='M'>
<re.Match object; span=(300, 301), match='M'>
<re.Match object; span=(309, 310), match='M'>
<re.Match object; span=(323, 324), match='M'>
<re.Match object; span=(329, 330), match='M'>


In [47]:
# step 2

# [ matches the char in brackets]
a = re.compile(r'Mr')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(279, 281), match='Mr'>
<re.Match object; span=(291, 293), match='Mr'>
<re.Match object; span=(309, 311), match='Mr'>
<re.Match object; span=(323, 325), match='Mr'>
<re.Match object; span=(329, 331), match='Mr'>


In [49]:
# step 3

# [ matches the char in brackets]
a = re.compile(r'Mr\.')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(279, 282), match='Mr.'>
<re.Match object; span=(323, 326), match='Mr.'>


In [50]:
# step 4

# [ matches the char in brackets]
a = re.compile(r'Mr\.\s')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(279, 283), match='Mr. '>
<re.Match object; span=(323, 327), match='Mr. '>


In [51]:
# step 5

# [ matches the char in brackets]
a = re.compile(r'Mr\.\s[A-Z]')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(279, 284), match='Mr. S'>
<re.Match object; span=(323, 328), match='Mr. T'>


In [61]:
# step 6 - use of star

# [ matches the char in brackets]
a = re.compile(r'Mr\.\s[A-Z][a-z]*')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(279, 290), match='Mr. Schafer'>
<re.Match object; span=(323, 328), match='Mr. T'>


In [62]:
# step 7 | --> or   ()

# [ matches the char in brackets]
a = re.compile(r'M(r|s)\.\s[A-Z][a-z]*')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(279, 290), match='Mr. Schafer'>
<re.Match object; span=(323, 328), match='Mr. T'>


In [64]:
# step 8

# [ matches the char in brackets]
a = re.compile(r'M(r|s|rs)\.?\s[A-Z][a-z]*')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(279, 290), match='Mr. Schafer'>
<re.Match object; span=(291, 299), match='Mr Smith'>
<re.Match object; span=(300, 308), match='Ms Davis'>
<re.Match object; span=(309, 322), match='Mrs. Robinson'>
<re.Match object; span=(323, 328), match='Mr. T'>


In [70]:
# step 8

# [ matches the char in brackets]
a = re.compile(r'M(r|s|rs)(.|_)?\s?[A-Z|a-z][a-z]*')
# From where you want to match
b = a.finditer(text_to_search)

for i in b:
    print(i)

<re.Match object; span=(279, 290), match='Mr. Schafer'>
<re.Match object; span=(291, 299), match='Mr Smith'>
<re.Match object; span=(300, 308), match='Ms Davis'>
<re.Match object; span=(309, 312), match='Mrs'>
<re.Match object; span=(323, 328), match='Mr. T'>
<re.Match object; span=(329, 337), match='Mr_hello'>


In [71]:
text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ\s
321-555-4321
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? { } [ ] \ | ( )
mohammed.israr11.com
321-555-4321
123.555.1234
123*555*1234
123.555.1234
800-555-1234
900-555-1234
987000000000
134000007770
Mr. Schafer
Mr Smith
Ms Davis
Mrs. Robinson
Mr. T
Mr_hello
'''


In [ ]:
regex to check whether its a valid email or no?

In [72]:
mail='''mohammed.israr11@gmail.com
mohammed.python@gmail.com
PYTHON.israr11@yahoo.com
mohammed.israr11@mama-earth.com 
mohammed_israr11@redif.com 
'''


In [82]:
mails='''PYTHON.israr11@yahoo.com'''


In [83]:
a=re.compile(r'\b[^A-Z][a-z]*(.|_)[a-z0-9]*@[a-z]*\.com') #not white space #? 0 0r 1
b=a.finditer(mails)
for i in b:
    print(i)


<re.Match object; span=(6, 24), match='.israr11@yahoo.com'>


In [81]:
import re
pattern = re.compile(r'[a-z]*(.|_)?[a-z0-9]*@[a-z]*\.com')

matches = pattern.finditer(mail)

for i in matches:
    print(i)


<re.Match object; span=(0, 26), match='mohammed.israr11@gmail.com'>
<re.Match object; span=(27, 52), match='mohammed.python@gmail.com'>
<re.Match object; span=(59, 77), match='.israr11@yahoo.com'>
<re.Match object; span=(111, 137), match='mohammed_israr11@redif.com'>


# Numpy

In [84]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [85]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


* matrix - maths 
* programing - array
* deep learning - tensor

# Numpy - Numerical python

* Its a python package used for computation and preocessing of single and multi dimensional array
* Its written in C - The speed is unmatchable 
* 

In [88]:
import numpy as np

In [ ]:
# 1. create an array with python list or tuple using array function

In [95]:
lst_1 = [1,2,3,4,5,6]

print(type(lst_1))

arr = np.array(lst_1)

print(arr , type(arr))

<class 'list'>
[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [92]:
lst_1 = (1,2,3,4,5,6)

print(type(lst_1))

arr = np.array(lst_1)

print(arr , type(arr))

<class 'tuple'>
[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [ ]:
print(dir(np))

In [94]:
lst_1 = {1:3434,2:4334,3:32434,4:343,5:343,6:343}

print(type(lst_1))

arr = np.array(lst_1)

print(arr , type(arr))

<class 'dict'>
{1: 3434, 2: 4334, 3: 32434, 4: 343, 5: 343, 6: 343} <class 'numpy.ndarray'>


In [99]:
lst_1 = [1,2,3,4,5,6]

arr = np.array(lst_1)

# few important attributes 

# Size of the array
print(arr.size)

# shape of the array
print(arr.shape)
# dim
print(arr.ndim)

6
(6,)
1


In [ ]:
scalar ?----> 0d ----45, 65,34
vector ?----> 1d -----> [1,2,3,4,5,6]
2d
3d
4d


In [101]:
lst_1 = [[1,2,3,4],[9,7,6,5],[3,6,7,98]]

print(type(lst_1))

arr = np.array(lst_1)

print(arr , type(arr))

<class 'list'>
[[ 1  2  3  4]
 [ 9  7  6  5]
 [ 3  6  7 98]] <class 'numpy.ndarray'>


In [117]:
lst_1 = [[[1,2,3],[4,5,6]]]

print(type(lst_1))

arr = np.array(lst_1)

print(arr , type(arr))

<class 'int'>
2 <class 'numpy.ndarray'>


In [ ]:
2. Create an array with arange function

In [105]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [107]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. using linspace

In [115]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [116]:
# zeros and zero like
