# Universal fuctions

In [1]:
import numpy as np

In [26]:
a = np.array([10,20,30,40])
b = np.array([5,10,15,20])
c = np.array([50,100,150,200])
d = np.array([5,10,15,20])
e = np.array([50,100,150,200])

In [12]:
a+b+c

array([ 65, 130, 195, 260])

In [25]:
np.add(a,b,c)

array([15, 30, 45, 60])

In [14]:
c

array([15, 30, 45, 60])

In [19]:
np.subtract(a,b)

array([ 5, 10, 15, 20])

In [21]:
c

array([ 50, 100, 150, 200])

In [22]:
np.multiply(a,b)

array([ 50, 200, 450, 800])

In [32]:
# product
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,4],[2,5],[3,6]])
a.dot(b)
# or
np.dot(a,b)

array([[14, 32],
       [32, 77]])

In [33]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [36]:
np.log([1,5,6,7])

array([0.        , 1.60943791, 1.79175947, 1.94591015])

In [37]:
np.sqrt([2,3,4,5])

array([1.41421356, 1.73205081, 2.        , 2.23606798])

In [38]:
np.square([1,2,3,4])

array([ 1,  4,  9, 16], dtype=int32)

In [40]:
np.sin([1,2,3,4])

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
# Statistics functions

mean - average
median - if the length  element is odd then its middle value, if its even it'll be (a+b)/2
mode - highest frequency
std - deviation
variance - 


In [42]:
age_in_years = np.array([35,65,17,58,29,45,19])

In [43]:
np.mean(age_in_years)

38.285714285714285

In [44]:
np.median(age_in_years)

35.0

In [45]:
np.std(age_in_years)

17.193971416203546

In [46]:
np.var(age_in_years)

295.6326530612245

In [ ]:
# Indexing and slicing in arrays

In [48]:
a = np.arange(5)**2
a

array([ 0,  1,  4,  9, 16], dtype=int32)

In [49]:
a[2]

4

In [50]:
a[-3]

4

In [51]:
a[2:4]

array([4, 9], dtype=int32)

In [54]:
a[2]

4

In [55]:
a

array([ 0,  1,  4,  9, 16], dtype=int32)

In [57]:
a[::2] = 100
a

array([100,   1, 100,   9, 100], dtype=int32)

In [58]:
# 2 D   6 
b = np.arange(6).reshape(2,3)

In [59]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
[[0,1,2],[3,4,5]]

In [62]:
b[1][:2]

array([3, 4])

In [65]:
b[1,:2]

array([3, 4])

In [72]:
a1 = np.arange(25).reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
a1[2,2:4]

array([12, 13])

In [79]:
#
a1[::2,2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [71]:
a1[::2,2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [102]:
b2 = np.arange(12).reshape(3,4)
b2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
a = b2[b2<6]

In [101]:
a.sum()

15

In [97]:
np.sum(np.extract(b2<6,b2))

15

In [105]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [111]:
b = a[a<6]

In [112]:
np.sum(b)

15

In [127]:
# Iterating
a = np.arange(25).reshape(5,5)

In [128]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [115]:


for element in a:
    print(element)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [118]:
for element in a:
    for i in element:
        print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [129]:
print(a)
print(a.flatten())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [121]:
for i in a.flatten():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [124]:
a = [[1,2,3,4],[2,3,5]]
for i in a:
    for j in i:
        print(j)

1
2
3
4
2
3
5


In [ ]:
# Splitting of the arrays

In [152]:
a1 = np.arange(12)**2
a1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [150]:
# array and how many splits do we need 
np.split(a1,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [151]:
np.split(a1,4)[2]

array([6, 7, 8])

In [138]:
a,b,c,d,e,f = np.split(a1,6)

In [153]:
a1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [156]:
# 
np.split(a1,[2,8,10])

[array([0, 1], dtype=int32),
 array([ 4,  9, 16, 25, 36, 49], dtype=int32),
 array([64, 81], dtype=int32),
 array([100, 121], dtype=int32)]

In [146]:
np.split(a1,[4,8,15])

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([], dtype=int32)]

In [148]:
np.split(a1,[3,5])

[array([0, 1, 2]), array([3, 4]), array([ 5,  6,  7,  8,  9, 10, 11])]

In [158]:
arr = np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [159]:
np.split(arr, 3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [162]:
# axis = 1, spltting the columns
np.split(arr, 3 , axis = 1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [163]:
# axis = 0, spltting the rows
np.split(arr, 3 , axis = 0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [164]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [165]:
# for horizontal split
np.hsplit(arr, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [166]:
np.vsplit(arr, 3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [ ]:

# copy and view 
# image manupulation

In [189]:
# Concatination
a = np.array([['israr', 'amitesh'],['anil', 'arwa']])
b = np.array([['bala', 'kalyani'],['lakshmi', 'maisumi']])

In [169]:
a

array([['israr', 'amitesh'],
       ['anil', 'arwa']], dtype='<U7')

In [170]:
b

array([['bala', 'kalyani'],
       ['lakshmi', 'maisumi']], dtype='<U7')

In [186]:
# axis = 0 ---> rows 
arr = np.concatenate((a,b))
arr

array([['israr', 'amitesh'],
       ['anil', 'arwa'],
       ['bala', 'kalyani'],
       ['lakshmi', 'maisumi']], dtype='<U7')

In [190]:
# axis = 1 ----columns
arr = np.concatenate((a,b), axis = 1)
arr

array([['israr', 'amitesh', 'bala', 'kalyani'],
       ['anil', 'arwa', 'lakshmi', 'maisumi']], dtype='<U7')

In [191]:
a = np.array([['israr', 'amitesh'],['anil', 'arwa']])
b = np.array([['bala', 'kalyani'],['lakshmi', 'maisumi']])

In [192]:
# rows 
np.vstack((a,b))

array([['israr', 'amitesh'],
       ['anil', 'arwa'],
       ['bala', 'kalyani'],
       ['lakshmi', 'maisumi']], dtype='<U7')

In [194]:
# columns
np.hstack((a,b))

array([['israr', 'amitesh', 'bala', 'kalyani'],
       ['anil', 'arwa', 'lakshmi', 'maisumi']], dtype='<U7')

In [ ]:
# copy and view 